type colors =
  | 'color--black'
  | 'color--black-90'
  | 'color--black-75'
  | 'color--black-75-opaque'
  | 'color--black-50'
  | 'color--black-25'
  | 'color--black-15'
  | 'color--black-10'
  | 'color--black-5'
  | 'color--white'
  | 'color__light--accent'
  | 'color__light--accent-medium'
  | 'color__light--accent-medium-opaque'
  | 'color__light--accent-dark'
  | 'color__dark--accent'
  | 'color__dark--accent-opaque'
  | 'color__dark--accent-medium'
  | 'color__dark--accent-medium-opaque'
  | 'color__dark--accent-dark'
  | 'color__light--gradient-hero'
  | 'color__light--gradient-project'
  | 'color__dark--gradient-hero'
  | 'color__dark--gradient-project';
export default colors;
